---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 1.0.5
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
---

```{python slideshow={'slide_type': 'skip'}}
from __future__ import print_function, division
from builtins import range, input
import pandas as pd
import json
import requests
from bs4 import BeautifulSoup as BS
import re
import warnings
import bokeh
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import codecs
from json import JSONDecoder
from functools import partial

from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

pd.options.display.max_rows = 9999
pd.options.display.max_columns = 9999
warnings.filterwarnings("ignore")
```

```{python slideshow={'slide_type': 'skip'}}
#pip install RISE
```

```{python slideshow={'slide_type': 'skip'}}
business_word_cloud=pd.read_pickle("data\\business_word_cloud.pkl")
```

# The restaurant business is over crowded
- There are more than 10000 different restaurants in Las Vegas.
- One fourth of them have more than one branch.
- However, we really want and dine in only small subset of all these restaurants.

## Can friend help us?

- Yes, I tend to find my friends' stuffs interesting
- What if I had only few friends, and what they like do not always attract me?
- They can only visit limited number of them. 

## Can Google help?
- Read the reviews which is very time consuming and not possible for many new opened restaurants.
- Yes, but only when we really know what we are looking for
- What if I just want some interesting music tracks?


```{python slideshow={'slide_type': 'slide'}}
myData=business_word_cloud.head(200)
text=""
for index, row in myData.iterrows():
    str1=""
    str1= (row['Restaurant']+" ")*row['Frequency']
    text=text+str1
wordcloud = WordCloud(max_font_size=30, max_words=200, background_color="white", collocations = False).generate(text)
plt.figure(figsize=(60,30))
plt.imshow(wordcloud, interpolation="bilinear")
plt.axis("off")
plt.show()
```
- In technical terms, a recommendation engine problem is to develop a
mathematical model or objective function which can predict how much a user
will like an item.

```{python}

```

```{python}

```
